// Week 3 and 4/Module 6 - Frontend/student-portal-vue/src/components/Header.vue
<template>

<header class="header">

<h1>Student Portal</h1>

<p>

Enrolled Courses :

{{ store.enrolledCourses.length }}

</p>

</header>

</template>

<script setup>

import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()

</script>

<style scoped>

.header{

    background:#1976d2;

    color:white;

    padding:20px;

    text-align:center;

    border-radius:10px;

}

</style>

// Week 3 and 4/Module 6 - Frontend/student-portal-react/src/components/Header.jsx
import { Link } from "react-router-dom";

import { useSelector } from "react-redux";

function Header() {

    const enrolledCourses = useSelector(

        state => state.enrollment.enrolledCourses

    );

    return (

        <header className="header">

            <h1>Student Portal</h1>

            <h3>

                Enrolled : {enrolledCourses.length}

            </h3>

            <nav>

                <ul className="nav-links">

                    <li><Link to="/">Home</Link></li>

                    <li><Link to="/courses">Courses</Link></li>

                    <li><Link to="/profile">Profile</Link></li>

                </ul>

            </nav>

        </header>

    );

}

export default Header;
